-- Insert scholarships from mockData.ts and new Indian domestic scholarships with proper UUIDs
INSERT INTO scholarships (
    id, title, amount, deadline, description, category, eligibility, provider, requirements, 
    eligibility_details, application_process, benefits, selection_criteria, contact_info, is_active
) VALUES 
-- Original scholarships from mockData.ts
('11111111-1111-1111-1111-111111111111', 'Fulbright Foreign Student Program', '$25,000 - $45,000', '2025-10-15', 
 'The prestigious Fulbright Program offers scholarships for Indian students to pursue Master''s and PhD degrees in the United States.',
 'International Students', 'Indian citizens with excellent academic record, leadership potential, and English proficiency', 
 'United States-India Educational Foundation',
 '["Bachelor''s degree with first class or high second class", "TOEFL/IELTS scores", "Statement of Purpose", "Three letters of recommendation", "Academic transcripts", "Research proposal (for PhD applicants)"]'::jsonb,
 '["Excellent academic background", "Leadership potential", "English proficiency", "Research experience"]'::jsonb,
 '["Online application", "Document submission", "Interview process", "Selection"]'::jsonb,
 '["Full tuition coverage", "Living allowance", "Health insurance", "Travel costs"]'::jsonb,
 '["Academic excellence (40%)", "Leadership potential (30%)", "English proficiency (20%)", "Research potential (10%)"]'::jsonb,
 '{"email": "fulbright@usief.org.in", "website": "https://www.usief.org.in", "phone": "+91-11-4209-0909"}'::jsonb,
 true),

('22222222-2222-2222-2222-222222222222', 'Inlaks Shivdasani Foundation Scholarship', '$100,000 - $150,000', '2025-11-15',
 'Merit-based scholarships for outstanding Indian students to pursue postgraduate studies at top universities in the US, UK, and Europe.',
 'Merit-Based', 'Indian citizens under 30 years, exceptional academic record, admission to top-tier universities',
 'Inlaks Shivdasani Foundation',
 '["Undergraduate degree with distinction", "Admission to partner universities", "GMAT/GRE/LSAT scores", "Personal statement", "Academic references", "Interview"]'::jsonb,
 '["Age under 30", "First class degree", "Admission to top universities", "Leadership qualities"]'::jsonb,
 '["Application submission", "Document review", "Interview", "Final selection"]'::jsonb,
 '["Full tuition", "Living expenses", "Travel allowance", "Book allowance"]'::jsonb,
 '["Academic merit (50%)", "Leadership (25%)", "University ranking (15%)", "Interview performance (10%)"]'::jsonb,
 '{"email": "scholarships@inlaks.org", "website": "https://www.inlaksfoundation.org"}'::jsonb,
 true),

-- Indian domestic scholarships
('dddddddd-dddd-dddd-dddd-dddddddddddd', 'INSPIRE Scholarship (DST)', '₹80,000/year + research fellowship', '2025-07-31',
 'Government of India scholarship for students pursuing Basic and Natural Sciences at undergraduate and postgraduate levels.',
 'Government', 'Indian citizens, top 1% in 12th boards or KVPY/NTSE qualified, pursuing Basic Sciences',
 'Department of Science and Technology, GoI',
 '["12th standard marks certificate", "Admission to recognized institution", "KVPY/NTSE qualification", "Bank account details", "Aadhar card", "Income certificate"]'::jsonb,
 '["Top 1% in 12th boards", "KVPY/NTSE qualification", "Basic Sciences stream", "Indian citizenship"]'::jsonb,
 '["Online application", "Document verification", "Merit list", "Fellowship award"]'::jsonb,
 '["Monthly scholarship", "Research fellowship", "Summer training", "Conference participation"]'::jsonb,
 '["Academic merit (60%)", "Board exam rank (25%)", "KVPY/NTSE score (15%)"]'::jsonb,
 '{"email": "inspire@dst.gov.in", "website": "https://online-inspire.gov.in"}'::jsonb,
 true),

('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'Prime Minister Research Fellowship (PMRF)', '₹80,000/month + research grant', '2025-05-31',
 'Prestigious fellowship for PhD in science and technology at IITs, IISc, and select institutions.',
 'Government Fellowship', 'BTech/Integrated MTech graduates from CFTIs with CGPA 8.0+',
 'Ministry of Education, GoI',
 '["BTech/MTech from IITs/NITs/IISERs/IISc", "CGPA 8.0 or above", "GATE/JAM/GPAT qualification", "Research proposal", "Statement of purpose", "Faculty recommendations"]'::jsonb,
 '["CFTIs graduate", "CGPA 8.0+", "GATE qualification", "Research aptitude"]'::jsonb,
 '["Online application", "Document verification", "Interview", "Selection"]'::jsonb,
 '["Monthly fellowship", "Annual research grant", "Conference funding", "International exposure"]'::jsonb,
 '["Academic performance (40%)", "Research proposal (30%)", "Interview (20%)", "Recommendations (10%)"]'::jsonb,
 '{"email": "pmrf@iitd.ac.in", "website": "https://pmrf.in"}'::jsonb,
 true),

('ffffffff-ffff-ffff-ffff-ffffffffffff', 'Aditya Birla Scholarship', '₹2,00,000/year', '2025-09-15',
 'Merit-based scholarship for engineering and management students at premier institutions like IITs, IIMs, and top law schools.',
 'Corporate Scholarship', 'Students admitted to IITs, IIMs, BITS Pilani, AIIMS, National Law Schools',
 'Aditya Birla Group',
 '["Admission to eligible institutions", "Excellent academic record", "JEE/CAT/CLAT scores", "Leadership qualities", "Community service experience", "Interview and group discussion"]'::jsonb,
 '["Premier institution admission", "Academic excellence", "Leadership potential", "Social commitment"]'::jsonb,
 '["Application submission", "Academic review", "Group discussion", "Personal interview", "Selection"]'::jsonb,
 '["Annual scholarship", "Mentorship program", "Internship opportunities", "Leadership development"]'::jsonb,
 '["Academic merit (40%)", "Leadership (30%)", "Interview performance (20%)", "Social impact (10%)"]'::jsonb,
 '{"email": "scholarships@adityabirla.com", "website": "https://www.adityabirla.com/scholarships"}'::jsonb,
 true),

('gggggggg-gggg-gggg-gggg-gggggggggggg', 'Reliance Foundation Scholarship', '₹2,00,000/year', '2025-10-31',
 'Need and merit-based scholarships for undergraduate students in engineering, medicine, and other professional courses.',
 'Corporate Scholarship', 'Undergraduate students in professional courses, family income <₹6 lakhs',
 'Reliance Foundation',
 '["Admission to recognized institution", "12th standard marks (minimum 60%)", "Family income certificate", "Entrance exam scores", "Academic transcripts", "Recommendation letters"]'::jsonb,
 '["Professional course admission", "Minimum 60% in 12th", "Family income below ₹6 lakhs", "Merit-cum-need basis"]'::jsonb,
 '["Online application", "Document verification", "Merit assessment", "Scholarship award"]'::jsonb,
 '["Annual scholarship", "Academic support", "Career guidance", "Skill development"]'::jsonb,
 '["Academic merit (50%)", "Financial need (30%)", "Course relevance (20%)"]'::jsonb,
 '{"email": "scholarships@ril.com", "website": "https://www.reliancefoundation.org/scholarships"}'::jsonb,
 true),

('hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh', 'KVPY Fellowship', '₹7,000/month (UG) + ₹28,000/month (PhD)', '2025-08-31',
 'National fellowship program in Basic Sciences for students from Class XI to PhD level.',
 'Science Fellowship', 'Students in Class XI, XII, 1st/2nd year BSc, MSc, integrated courses',
 'Indian Institute of Science',
 '["Academic transcripts", "KVPY aptitude test qualification", "Interview performance", "Commitment to pursue research career", "Medical fitness certificate"]'::jsonb,
 '["Science stream students", "KVPY test qualification", "Research aptitude", "Age limit as per stream"]'::jsonb,
 '["KVPY exam", "Interview", "Merit list", "Fellowship award"]'::jsonb,
 '["Monthly fellowship", "Annual contingency", "Research opportunities", "Summer programs"]'::jsonb,
 '["KVPY exam score (70%)", "Interview performance (30%)"]'::jsonb,
 '{"email": "kvpy@iisc.ac.in", "website": "http://kvpy.iisc.ernet.in"}'::jsonb,
 true),

('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 'CSIR NET JRF Fellowship', '₹31,000/month + HRA', '2025-06-15',
 'Fellowship for pursuing PhD in Science and Technology. Includes Junior Research Fellowship and Senior Research Fellowship.',
 'Research Fellowship', 'Postgraduate in Science/Engineering with NET qualification',
 'Council of Scientific and Industrial Research',
 '["Master''s degree in Science/Technology", "CSIR NET/GATE qualification", "Research proposal", "Supervisor''s consent letter", "University admission letter", "Medical certificate"]'::jsonb,
 '["Postgraduate degree", "NET qualification", "Research aptitude", "PhD admission"]'::jsonb,
 '["NET exam", "PhD admission", "Fellowship application", "Award"]'::jsonb,
 '["Monthly fellowship", "House rent allowance", "Contingency grant", "Conference funding"]'::jsonb,
 '["NET exam score (60%)", "Academic record (25%)", "Research proposal (15%)"]'::jsonb,
 '{"email": "jrf@csirhrdg.res.in", "website": "https://csirhrdg.res.in"}'::jsonb,
 true),

('jjjjjjjj-jjjj-jjjj-jjjj-jjjjjjjjjjjj', 'UGC NET JRF', '₹31,000/month + HRA', '2025-09-30',
 'University Grants Commission fellowship for pursuing PhD in humanities, social sciences, and other subjects.',
 'Research Fellowship', 'Postgraduate degree holders who qualify UGC NET',
 'University Grants Commission',
 '["Master''s degree (minimum 55% marks)", "UGC NET qualification", "PhD admission in recognized university", "Research proposal", "Supervisor details"]'::jsonb,
 '["55% in Masters", "UGC NET qualified", "Age limit 28 years", "PhD admission"]'::jsonb,
 '["UGC NET exam", "PhD admission", "Fellowship application", "Selection"]'::jsonb,
 '["Monthly fellowship", "House rent allowance", "Research grant", "Conference support"]'::jsonb,
 '["NET exam rank (70%)", "Academic performance (30%)"]'::jsonb,
 '{"email": "ugcnet@nta.ac.in", "website": "https://ugcnet.nta.nic.in"}'::jsonb,
 true),

('kkkkkkkk-kkkk-kkkk-kkkk-kkkkkkkkkkkk', 'Sitaram Jindal Foundation Scholarship', '₹48,000/year', '2025-11-30',
 'Merit-cum-means scholarship for economically disadvantaged meritorious students pursuing professional courses.',
 'Merit-cum-Means', 'Students in professional courses, family income <₹2.5 lakhs, good academic record',
 'Sitaram Jindal Foundation',
 '["Academic transcripts", "Income certificate", "Caste certificate (if applicable)", "Entrance exam scorecard", "Bank account details", "College admission letter"]'::jsonb,
 '["Professional course student", "Income below ₹2.5 lakhs", "Good academic record", "Merit basis"]'::jsonb,
 '["Application submission", "Document verification", "Merit assessment", "Scholarship award"]'::jsonb,
 '["Annual scholarship", "Educational support", "Skill development", "Career guidance"]'::jsonb,
 '["Academic merit (60%)", "Financial need (40%)"]'::jsonb,
 '{"email": "scholarships@sitaramjindalfoundation.org", "website": "https://www.sitaramjindalfoundation.org"}'::jsonb,
 true),

('llllllll-llll-llll-llll-llllllllllll', 'ONGC Scholarship', '₹48,000/year', '2025-08-31',
 'Scholarship for economically disadvantaged students pursuing technical/professional courses in India.',
 'Corporate Scholarship', 'Students in technical/professional courses, family income <₹4.5 lakhs, good academic record',
 'Oil and Natural Gas Corporation',
 '["Course admission certificate", "Previous academic records", "Income certificate", "Bank account details", "Aadhar card", "Character certificate"]'::jsonb,
 '["Technical/professional course", "Income below ₹4.5 lakhs", "Good academics", "Indian citizen"]'::jsonb,
 '["Online application", "Document verification", "Merit list", "Scholarship award"]'::jsonb,
 '["Annual scholarship", "Educational assistance", "Career support", "Skill training"]'::jsonb,
 '["Academic performance (70%)", "Financial need (30%)"]'::jsonb,
 '{"email": "scholarships@ongc.co.in", "website": "https://www.ongcindia.com/scholarships"}'::jsonb,
 true),

('mmmmmmmm-mmmm-mmmm-mmmm-mmmmmmmmmmmm', 'Azim Premji Foundation Scholarship', 'Full tuition + living expenses', '2025-06-30',
 'Comprehensive scholarship for students from economically weaker sections to pursue higher education.',
 'NGO Scholarship', 'Meritorious students from low-income families, commitment to social development',
 'Azim Premji Foundation',
 '["Academic excellence", "Family income <₹2 lakhs", "Social development commitment", "Leadership potential", "Community service record", "Detailed application essay"]'::jsonb,
 '["Income below ₹2 lakhs", "Academic merit", "Social commitment", "Leadership qualities"]'::jsonb,
 '["Application submission", "Document review", "Interview", "Selection"]'::jsonb,
 '["Full scholarship", "Living allowance", "Mentorship", "Social work opportunities"]'::jsonb,
 '["Academic merit (40%)", "Financial need (30%)", "Social commitment (20%)", "Leadership (10%)"]'::jsonb,
 '{"email": "scholarships@azimpremjifoundation.org", "website": "https://azimpremjifoundation.org"}'::jsonb,
 true)

ON CONFLICT (id) DO NOTHING;