-- Insert scholarships and colleges from mockData.ts with proper UUIDs
INSERT INTO scholarships (
    id, title, amount, deadline, description, category, eligibility, provider, requirements, 
    eligibility_details, application_process, benefits, selection_criteria, contact_info, is_active
) VALUES 
-- Original scholarships from mockData.ts
(gen_random_uuid(), 'Fulbright Foreign Student Program', '$25,000 - $45,000', '2025-10-15', 
 'The prestigious Fulbright Program offers scholarships for Indian students to pursue Master''s and PhD degrees in the United States.',
 'International Students', 'Indian citizens with excellent academic record, leadership potential, and English proficiency', 
 'United States-India Educational Foundation',
 '["Bachelor''s degree with first class or high second class", "TOEFL/IELTS scores", "Statement of Purpose", "Three letters of recommendation", "Academic transcripts", "Research proposal (for PhD applicants)"]'::jsonb,
 '["Excellent academic background", "Leadership potential", "English proficiency", "Research experience"]'::jsonb,
 '["Online application", "Document submission", "Interview process", "Selection"]'::jsonb,
 '["Full tuition coverage", "Living allowance", "Health insurance", "Travel costs"]'::jsonb,
 '["Academic excellence (40%)", "Leadership potential (30%)", "English proficiency (20%)", "Research potential (10%)"]'::jsonb,
 '{"email": "fulbright@usief.org.in", "website": "https://www.usief.org.in", "phone": "+91-11-4209-0909"}'::jsonb,
 true),

(gen_random_uuid(), 'Tata Scholarship at Cornell University', 'Full tuition + living expenses', '2025-12-01',
 'Comprehensive scholarship for Indian students to pursue undergraduate studies at Cornell University.',
 'Undergraduate', 'Indian citizens with outstanding academic achievement and financial need',
 'Tata Education and Development Trust',
 '["Excellent high school grades (90%+ or equivalent)", "SAT/ACT scores", "Common Application", "Essays and personal statements", "Letters of recommendation", "Financial aid application"]'::jsonb,
 '["Indian citizenship", "Outstanding academics", "Financial need", "Leadership potential"]'::jsonb,
 '["Common Application", "Cornell admission", "Financial aid review", "Scholarship award"]'::jsonb,
 '["Full tuition", "Living expenses", "Books allowance", "Health insurance"]'::jsonb,
 '["Academic merit (50%)", "Financial need (30%)", "Leadership (20%)"]'::jsonb,
 '{"email": "finaid@cornell.edu", "website": "https://admissions.cornell.edu/financial-aid"}'::jsonb,
 true),

(gen_random_uuid(), 'Rhodes Scholarship', 'Full funding for 2-3 years', '2025-09-30',
 'One of the world''s most prestigious scholarships for postgraduate study at the University of Oxford.',
 'Prestigious Award', 'Indian citizens aged 19-25, exceptional academic achievement, leadership, and character',
 'Rhodes Trust',
 '["Bachelor''s degree with first class honors", "Demonstrated leadership", "Academic transcripts", "Personal statement", "Five to eight references", "Interview process"]'::jsonb,
 '["Age 19-25", "First class honors", "Leadership experience", "Character excellence"]'::jsonb,
 '["Application submission", "Reference collection", "Interview rounds", "Final selection"]'::jsonb,
 '["Full Oxford fees", "Living stipend", "Travel allowance", "Research funding"]'::jsonb,
 '["Academic excellence (25%)", "Leadership (25%)", "Character (25%)", "Commitment to service (25%)"]'::jsonb,
 '{"email": "info@rhodeshouse.ox.ac.uk", "website": "https://www.rhodeshouse.ox.ac.uk"}'::jsonb,
 true),

-- Indian domestic scholarships
(gen_random_uuid(), 'INSPIRE Scholarship (DST)', '₹80,000/year + research fellowship', '2025-07-31',
 'Government of India scholarship for students pursuing Basic and Natural Sciences at undergraduate and postgraduate levels.',
 'Government', 'Indian citizens, top 1% in 12th boards or KVPY/NTSE qualified, pursuing Basic Sciences',
 'Department of Science and Technology, GoI',
 '["12th standard marks certificate", "Admission to recognized institution", "KVPY/NTSE qualification", "Bank account details", "Aadhar card", "Income certificate"]'::jsonb,
 '["Top 1% in 12th boards", "KVPY/NTSE qualification", "Basic Sciences stream", "Indian citizenship"]'::jsonb,
 '["Online application", "Document verification", "Merit list", "Fellowship award"]'::jsonb,
 '["Monthly scholarship", "Research fellowship", "Summer training", "Conference participation"]'::jsonb,
 '["Academic merit (60%)", "Board exam rank (25%)", "KVPY/NTSE score (15%)"]'::jsonb,
 '{"email": "inspire@dst.gov.in", "website": "https://online-inspire.gov.in"}'::jsonb,
 true),

(gen_random_uuid(), 'Prime Minister Research Fellowship (PMRF)', '₹80,000/month + research grant', '2025-05-31',
 'Prestigious fellowship for PhD in science and technology at IITs, IISc, and select institutions.',
 'Government Fellowship', 'BTech/Integrated MTech graduates from CFTIs with CGPA 8.0+',
 'Ministry of Education, GoI',
 '["BTech/MTech from IITs/NITs/IISERs/IISc", "CGPA 8.0 or above", "GATE/JAM/GPAT qualification", "Research proposal", "Statement of purpose", "Faculty recommendations"]'::jsonb,
 '["CFTIs graduate", "CGPA 8.0+", "GATE qualification", "Research aptitude"]'::jsonb,
 '["Online application", "Document verification", "Interview", "Selection"]'::jsonb,
 '["Monthly fellowship", "Annual research grant", "Conference funding", "International exposure"]'::jsonb,
 '["Academic performance (40%)", "Research proposal (30%)", "Interview (20%)", "Recommendations (10%)"]'::jsonb,
 '{"email": "pmrf@iitd.ac.in", "website": "https://pmrf.in"}'::jsonb,
 true),

(gen_random_uuid(), 'KVPY Fellowship', '₹7,000/month (UG) + ₹28,000/month (PhD)', '2025-08-31',
 'National fellowship program in Basic Sciences for students from Class XI to PhD level.',
 'Science Fellowship', 'Students in Class XI, XII, 1st/2nd year BSc, MSc, integrated courses',
 'Indian Institute of Science',
 '["Academic transcripts", "KVPY aptitude test qualification", "Interview performance", "Commitment to pursue research career", "Medical fitness certificate"]'::jsonb,
 '["Science stream students", "KVPY test qualification", "Research aptitude", "Age limit as per stream"]'::jsonb,
 '["KVPY exam", "Interview", "Merit list", "Fellowship award"]'::jsonb,
 '["Monthly fellowship", "Annual contingency", "Research opportunities", "Summer programs"]'::jsonb,
 '["KVPY exam score (70%)", "Interview performance (30%)"]'::jsonb,
 '{"email": "kvpy@iisc.ac.in", "website": "http://kvpy.iisc.ernet.in"}'::jsonb,
 true),

(gen_random_uuid(), 'CSIR NET JRF Fellowship', '₹31,000/month + HRA', '2025-06-15',
 'Fellowship for pursuing PhD in Science and Technology. Includes Junior Research Fellowship and Senior Research Fellowship.',
 'Research Fellowship', 'Postgraduate in Science/Engineering with NET qualification',
 'Council of Scientific and Industrial Research',
 '["Master''s degree in Science/Technology", "CSIR NET/GATE qualification", "Research proposal", "Supervisor''s consent letter", "University admission letter", "Medical certificate"]'::jsonb,
 '["Postgraduate degree", "NET qualification", "Research aptitude", "PhD admission"]'::jsonb,
 '["NET exam", "PhD admission", "Fellowship application", "Award"]'::jsonb,
 '["Monthly fellowship", "House rent allowance", "Contingency grant", "Conference funding"]'::jsonb,
 '["NET exam score (60%)", "Academic record (25%)", "Research proposal (15%)"]'::jsonb,
 '{"email": "jrf@csirhrdg.res.in", "website": "https://csirhrdg.res.in"}'::jsonb,
 true),

(gen_random_uuid(), 'Aditya Birla Scholarship', '₹2,00,000/year', '2025-09-15',
 'Merit-based scholarship for engineering and management students at premier institutions like IITs, IIMs, and top law schools.',
 'Corporate Scholarship', 'Students admitted to IITs, IIMs, BITS Pilani, AIIMS, National Law Schools',
 'Aditya Birla Group',
 '["Admission to eligible institutions", "Excellent academic record", "JEE/CAT/CLAT scores", "Leadership qualities", "Community service experience", "Interview and group discussion"]'::jsonb,
 '["Premier institution admission", "Academic excellence", "Leadership potential", "Social commitment"]'::jsonb,
 '["Application submission", "Academic review", "Group discussion", "Personal interview", "Selection"]'::jsonb,
 '["Annual scholarship", "Mentorship program", "Internship opportunities", "Leadership development"]'::jsonb,
 '["Academic merit (40%)", "Leadership (30%)", "Interview performance (20%)", "Social impact (10%)"]'::jsonb,
 '{"email": "scholarships@adityabirla.com", "website": "https://www.adityabirla.com/scholarships"}'::jsonb,
 true),

(gen_random_uuid(), 'UGC NET JRF', '₹31,000/month + HRA', '2025-09-30',
 'University Grants Commission fellowship for pursuing PhD in humanities, social sciences, and other subjects.',
 'Research Fellowship', 'Postgraduate degree holders who qualify UGC NET',
 'University Grants Commission',
 '["Master''s degree (minimum 55% marks)", "UGC NET qualification", "PhD admission in recognized university", "Research proposal", "Supervisor details"]'::jsonb,
 '["55% in Masters", "UGC NET qualified", "Age limit 28 years", "PhD admission"]'::jsonb,
 '["UGC NET exam", "PhD admission", "Fellowship application", "Selection"]'::jsonb,
 '["Monthly fellowship", "House rent allowance", "Research grant", "Conference support"]'::jsonb,
 '["NET exam rank (70%)", "Academic performance (30%)"]'::jsonb,
 '{"email": "ugcnet@nta.ac.in", "website": "https://ugcnet.nta.nic.in"}'::jsonb,
 true);

-- Add more colleges from mockData.ts
INSERT INTO colleges (
    id, name, location, state, type, acceptance_rate, tuition, enrollment, ranking, description, 
    majors, rating, highlights, founded, campus, student_faculty_ratio, graduation_rate, 
    image_url, is_active
) VALUES 
(gen_random_uuid(), 'University of Rochester', 'Rochester, NY', 'New York', 'Private Research University', 
 '30%', '$63,150/year', '12,000', 25, 
 'A top-tier research university offering excellent need-based financial aid and merit scholarships for international students.',
 '["Engineering", "Business", "Computer Science", "Medicine", "Optics"]'::jsonb, 4.4,
 '["Generous financial aid", "Strong research programs", "Need-aware for internationals", "Merit scholarships available"]'::jsonb,
 1850, '154 acres', '10:1', '87%', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', true),

(gen_random_uuid(), 'Colby College', 'Waterville, ME', 'Maine', 'Private Liberal Arts College',
 '13%', '$62,000/year', '2,000', 12,
 'Elite liberal arts college with need-blind admissions for domestic students and generous aid for international students.',
 '["Liberal Arts", "Environmental Studies", "Economics", "Government", "Psychology"]'::jsonb, 4.5,
 '["Need-blind domestically", "Beautiful campus", "Strong alumni network", "Generous financial aid"]'::jsonb,
 1813, '714 acres', '10:1', '91%', 'https://images.unsplash.com/photo-1486591978090-58e04e67ffc7?w=400', true),

(gen_random_uuid(), 'Trinity College', 'Hartford, CT', 'Connecticut', 'Private Liberal Arts College',
 '34%', '$60,000/year', '2,400', 46,
 'Prestigious liberal arts college offering significant financial aid and merit scholarships to qualified international students.',
 '["Liberal Arts", "Engineering", "Computer Science", "Economics", "Neuroscience"]'::jsonb, 4.2,
 '["Strong financial aid", "Small classes", "Research opportunities", "Alumni network"]'::jsonb,
 1823, '100 acres', '9:1', '85%', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400', true),

(gen_random_uuid(), 'Dickinson College', 'Carlisle, PA', 'Pennsylvania', 'Private Liberal Arts College',
 '41%', '$58,000/year', '2,300', 51,
 'Liberal arts college with strong international programs and generous financial aid for students from developing countries.',
 '["Liberal Arts", "International Business", "Environmental Studies", "Political Science"]'::jsonb, 4.3,
 '["International focus", "Study abroad programs", "Need-based aid", "Sustainable campus"]'::jsonb,
 1783, '144 acres', '9:1', '84%', 'https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=400', true),

(gen_random_uuid(), 'Beloit College', 'Beloit, WI', 'Wisconsin', 'Private Liberal Arts College',
 '67%', '$55,000/year', '1,200', 105,
 'Innovative liberal arts college known for generous financial aid and strong support for international students.',
 '["Liberal Arts", "Anthropology", "Creative Writing", "Environmental Studies", "Theater"]'::jsonb, 4.1,
 '["Generous aid packages", "Innovative curriculum", "Strong community", "International diversity"]'::jsonb,
 1846, '40 acres', '11:1', '75%', 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400', true);