// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brirfkbuebpdqzwnsnjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyaXJma2J1ZWJwZHF6d25zbmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDM0NDcsImV4cCI6MjA2ODYxOTQ0N30.ZSBHVNht-UP0QD0-HQpAqiQ0t1IEux6MZAB4uM8Y6ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});